language: csharp
dist: trusty
sudo: required
before_install:
  - chmod +x build.sh
mono: none
dotnet: 2.0.3 # https://www.microsoft.com/net/download/linux
branches:
  only:
    - master
    - develop
script:
  - ./build.sh

